#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Jidai <jidai@github.com>
#

# Profiling mode START
# zmodload zsh/zprof

export ZSH_CUSTOM="$HOME/.zprezto/"

fpath=(~/.zprezto/my_completions $fpath)
autoload -U compinit && compinit

export ZSH_CUSTOM="$HOME/.zprezto/"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# History filter with command line beginning
#

autoload -Uz up-line-or-beginning-search
autoload -Uz down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '\eOA' up-line-or-beginning-search
bindkey '\e[A' up-line-or-beginning-search
bindkey '\eOB' down-line-or-beginning-search
bindkey '\e[B' down-line-or-beginning-search


#
# Use hub as git client, alias hub=git
#

eval "$(hub alias -s)"


#
# Load Pyenv
#

if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"

  pyenv virtualenvwrapper
fi


#
# Load NVM
#

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


#
# Aliases
#

alias venv="source ~/.virtualenvs/py34-www/bin/activate"
alias ma_tunnel='ssh -L 5432:localhost:5432 dev.meilleursagents.org'
alias ma_sync_to_dev="rsync -rlK --delete --exclude 'temp' --exclude 'data1' --exclude 'vendors' --exclude
'static/build' --exclude 'static/mypro' --exclude 'newrelic.ini' --exclude 'node_modules' --exclude 'build' --
exclude 'bower_components' --exclude '.git' /Users/jordid/MAWork/MeilleursAgents/ jordid@dev.meilleursagents.org:/
home/jordid/meilleursagents/"
alias pi_sync_to_dev="rsync -rlK --delete --exclude 'vendors' --exclude 'newrelic.ini' --exclude '.idea' --
exclude 'node_modules' --exclude 'build' --exclude 'bower_components' --exclude '.git' /Users/jordid/MAWork/
PrixImmobilier/ jordid@dev.meilleursagents.org:/home/jordid/PrixImmobilier/"

alias rm_node_modules="find . -name \"nodemodules\" -type d -prune -exec rm -rf '{}' +"

alias tt="timetracker"
alias tttl="timetracker task list"
alias tttr="timetracker task report"
alias tttb="timetracker task start"
alias ttts="timetracker task stop"
alias ttte="timetracker task edit"
alias ttjl="timetracker journal list"
alias ttja="timetracker journal add"

alias selenium-chrome="open vnc://localhost:secret@localhost:5900"
alias selenium-firefox="open vnc://localhost:secret@localhost:5901"

alias git_clean_branches="git branch --merged | egrep -v \"(^\\*|master|dev)\" | xargs git branch -d"
alias ...='cd `git rev-parse --show-toplevel`'
alias gitco="git branch | fzf | xargs git checkout"

function mkcd () {
    mkdir $1 && cd $1
}

if [[ -s "$HOME/.zsh_custom" ]]; then
    source "$HOME/.zsh_custom"
fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Profiling mode STOP
# zprof
